plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'java'
    id 'maven-publish'
    id 'idea'
}

idea {
    module {
        inheritOutputDirs = true
    }
}

def staticArchivesName = project.archives_base_name
def staticModName = project.mod_name
def staticModVersion = project.mod_version
def staticModDescription = project.mod_description
def staticMavenGroup = project.maven_group
def staticMcVersion = project.minecraft_version
def staticLoaderVersion = project.loader_version
def staticJavaVersion = project.java_version

version = staticModVersion
group = staticMavenGroup

base { archivesName = staticArchivesName }

repositories {
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    maven { url = "https://jitpack.io" }
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    // Minecraft
    minecraft "com.mojang:minecraft:${staticMcVersion}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${staticLoaderVersion}"

    // Compatible Mods (required by BlackOut transitive dependencies)
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "maven.modrinth:sodium:${project.sodium_version}-fabric"
    modImplementation "com.github.cabaletta.baritone:baritone-api:${project.baritone_api_version}"

    // BlackOut Client
    modImplementation "com.github.LimonTH:BlackOut-CE:${project.blackout_version}"
}

processResources {
    inputs.property("id", staticArchivesName)
    inputs.property("version", staticModVersion)
    inputs.property("name", staticModName)
    inputs.property("description", staticModDescription)
    inputs.property("minecraft_version", staticMcVersion)
    inputs.property("loader_version", staticLoaderVersion)
    inputs.property("java_version", staticJavaVersion)

    filesMatching("fabric.mod.json") {
        expand(
                "id": staticArchivesName,
                "version": staticModVersion,
                "name": staticModName,
                "description": staticModDescription,
                "minecraft_version": staticMcVersion,
                "loader_version": staticLoaderVersion,
                "java_version": staticJavaVersion
        )
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(JavaCompile).configureEach {
    it.options.setRelease(staticJavaVersion.toInteger())
    it.options.encoding = "UTF-8"
}

java {
    withSourcesJar()
    setSourceCompatibility(JavaVersion.toVersion(staticJavaVersion))
    setTargetCompatibility(JavaVersion.toVersion(staticJavaVersion))
}

jar {
    inputs.property("archivesName", staticArchivesName)

    from("LICENSE") {
        rename { "LICENSE_${staticArchivesName}" }
    }

    manifest {
        attributes([
                "Specification-Title": staticModName,
                "Specification-Vendor": "LimonTH",
                "Specification-Version": "1",
                "Implementation-Title": staticModName,
                "Implementation-Version": staticModVersion,
                "Implementation-Vendor": "LimonTH",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
        ])
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = staticArchivesName
            groupId = staticMavenGroup
            version = staticModVersion
            from components.java
        }
    }
}