org.gradle.jvmargs=-Xmx1G

loom_version=1.16-SNAPSHOT
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.2
java_version=21

mod_version=1.0.0
maven_group=com.example
archives_base_name=example-addon
mod_name=Example Addon
mod_description=An example BlackOut addon.

fabric_api_version=0.119.4+1.21.4
sodium_version=mc1.21.4-0.6.13
baritone_api_version=1.2.15

blackout_version=2.2.3